-- PlayerScriptService.SharedClient.Settings exports
return {
	SettingsMenuController = require(script.SettingsMenuController),
	SettingsMenuUi = require(script.SettingsMenuUi),
	SettingsAudioController = require(script.SettingsAudioController),
	SettingsHudLayoutController = require(script.SettingsHudLayoutController),
	SettingsHudLayoutService = require(script.SettingsHudLayoutService),
	SettingsPayloadBuilder = require(script.SettingsPayloadBuilder),
	SettingsRemotesUtil = require(script.SettingsRemotesUtil),
	SettingsReturnToLobbyController = require(script.SettingsReturnToLobbyController),
	SettingsUi = require(script.SettingsUi),
	SettingsVisibilityController = require(script.SettingsVisibilityController),
	HudMoveModeInput = require(script.HudMoveModeInput),
}
