-- ReplicatedStorage.Shared exports
return {
	Classes = require(script.Classes),
	Enemy = require(script.Enemy),
	Player = require(script.Player),
	Remotes = require(script.Remotes),
	Settings = require(script.Settings),
	Shop = require(script.Shop),
	Waves = require(script.Waves),
	Pickups = require(script.Pickups),
	DifficultyConfig = require(script.DifficultyConfig),
	SentryConstants = require(script.SentryConstants),
	GameConfig = require(script.GameConfig),
}
