local RemoteNames = {
	Folder = "Remotes",
	WaveState = "WaveState",
	ReturnToLobby = "ReturnToLobby",
	MapVote = "MapVote",
	TeleportLoading = "TeleportLoading",
	ShopOpen = "ShopOpen",
	ShopGetCatalog = "ShopGetCatalog",
	ShopBuyWeapon = "ShopBuyWeapon",
	ShopBuyAmmo = "ShopBuyAmmo",
	WeaponAim = "WeaponAim",
	WeaponFire = "WeaponFire",
	WeaponReload = "WeaponReload",
	DamageIndicator = "DamageIndicator",
	ClassGetData = "ClassGetData",
	ClassSelect = "ClassSelect",
	ClassState = "ClassState",
	SettingsGet = "SettingsGet",
	SettingsSave = "SettingsSave",
	EditOfflinePlayerData = "EditOfflinePlayerData",
}

return RemoteNames
